<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace Google\Api\Ads\AdWords\v201607;


/**
   * CustomParameter is used to map a custom parameter key to its value.
   * @package Google_Api_Ads_AdWords_v201607
   * @subpackage v201607
   */
class CustomParameter
{
    const WSDL_NAMESPACE = 'https://adwords.google.com/api/adwords/cm/v201607';
    const XSI_TYPE = 'CustomParameter';
    /**
     * @access public
     * @var string
     */
    public $key;
    /**
     * @access public
     * @var string
     */
    public $value;
    /**
     * @access public
     * @var boolean
     */
    public $isRemove;
    /**
     * Gets the namesapce of this class
     * @return string the namespace of this class
     */
    public function getNamespace()
    {
        return self::WSDL_NAMESPACE;
    }
    /**
     * Gets the xsi:type name of this class
     * @return string the xsi:type name of this class
     */
    public function getXsiTypeName()
    {
        return self::XSI_TYPE;
    }
    public function __construct($key = null, $value = null, $isRemove = null)
    {
        $this->key = $key;
        $this->value = $value;
        $this->isRemove = $isRemove;
    }
}
