<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace Google\Api\Ads\AdWords\v201607;


/**
   * Represents a money amount with currency.
   * @package Google_Api_Ads_AdWords_v201607
   * @subpackage v201607
   */
class MoneyWithCurrency extends ComparableValue
{
    const WSDL_NAMESPACE = 'https://adwords.google.com/api/adwords/cm/v201607';
    const XSI_TYPE = 'MoneyWithCurrency';
    /**
     * @access public
     * @var Money
     */
    public $money;
    /**
     * @access public
     * @var string
     */
    public $currencyCode;
    /**
     * Gets the namesapce of this class
     * @return string the namespace of this class
     */
    public function getNamespace()
    {
        return self::WSDL_NAMESPACE;
    }
    /**
     * Gets the xsi:type name of this class
     * @return string the xsi:type name of this class
     */
    public function getXsiTypeName()
    {
        return self::XSI_TYPE;
    }
    public function __construct($money = null, $currencyCode = null, $ComparableValueType = null)
    {
        parent::__construct();
        $this->money = $money;
        $this->currencyCode = $currencyCode;
        $this->ComparableValueType = $ComparableValueType;
    }
}
