<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace Google\Api\Ads\AdWords\v201607;


/**
   * Represents a price extension.
   * @package Google_Api_Ads_AdWords_v201607
   * @subpackage v201607
   */
class PriceFeedItem extends ExtensionFeedItem
{
    const WSDL_NAMESPACE = 'https://adwords.google.com/api/adwords/cm/v201607';
    const XSI_TYPE = 'PriceFeedItem';
    /**
     * @access public
     * @var tnsPriceExtensionType
     */
    public $priceExtensionType;
    /**
     * @access public
     * @var tnsPriceExtensionPriceQualifier
     */
    public $priceQualifier;
    /**
     * @access public
     * @var string
     */
    public $trackingUrlTemplate;
    /**
     * @access public
     * @var string
     */
    public $language;
    /**
     * @access public
     * @var PriceTableRow[]
     */
    public $tableRows;
    /**
     * Gets the namesapce of this class
     * @return string the namespace of this class
     */
    public function getNamespace()
    {
        return self::WSDL_NAMESPACE;
    }
    /**
     * Gets the xsi:type name of this class
     * @return string the xsi:type name of this class
     */
    public function getXsiTypeName()
    {
        return self::XSI_TYPE;
    }
    public function __construct($priceExtensionType = null, $priceQualifier = null, $trackingUrlTemplate = null, $language = null, $tableRows = null, $feedId = null, $feedItemId = null, $status = null, $feedType = null, $startTime = null, $endTime = null, $devicePreference = null, $scheduling = null, $campaignTargeting = null, $adGroupTargeting = null, $keywordTargeting = null, $geoTargeting = null, $geoTargetingRestriction = null, $policyData = null, $ExtensionFeedItemType = null)
    {
        parent::__construct();
        $this->priceExtensionType = $priceExtensionType;
        $this->priceQualifier = $priceQualifier;
        $this->trackingUrlTemplate = $trackingUrlTemplate;
        $this->language = $language;
        $this->tableRows = $tableRows;
        $this->feedId = $feedId;
        $this->feedItemId = $feedItemId;
        $this->status = $status;
        $this->feedType = $feedType;
        $this->startTime = $startTime;
        $this->endTime = $endTime;
        $this->devicePreference = $devicePreference;
        $this->scheduling = $scheduling;
        $this->campaignTargeting = $campaignTargeting;
        $this->adGroupTargeting = $adGroupTargeting;
        $this->keywordTargeting = $keywordTargeting;
        $this->geoTargeting = $geoTargeting;
        $this->geoTargetingRestriction = $geoTargetingRestriction;
        $this->policyData = $policyData;
        $this->ExtensionFeedItemType = $ExtensionFeedItemType;
    }
}
