<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace Google\Api\Ads\AdWords\v201607;


/**
   * A descriptor for finding {@link TargetingIdea}s that match the specified criteria.
   * @package Google_Api_Ads_AdWords_v201607
   * @subpackage v201607
   */
class TargetingIdeaSelector
{
    const WSDL_NAMESPACE = 'https://adwords.google.com/api/adwords/o/v201607';
    const XSI_TYPE = 'TargetingIdeaSelector';
    /**
     * @access public
     * @var SearchParameter[]
     */
    public $searchParameters;
    /**
     * @access public
     * @var tnsIdeaType
     */
    public $ideaType;
    /**
     * @access public
     * @var tnsRequestType
     */
    public $requestType;
    /**
     * @access public
     * @var tnsAttributeType[]
     */
    public $requestedAttributeTypes;
    /**
     * @access public
     * @var Paging
     */
    public $paging;
    /**
     * @access public
     * @var string
     */
    public $localeCode;
    /**
     * @access public
     * @var string
     */
    public $currencyCode;
    /**
     * Gets the namesapce of this class
     * @return string the namespace of this class
     */
    public function getNamespace()
    {
        return self::WSDL_NAMESPACE;
    }
    /**
     * Gets the xsi:type name of this class
     * @return string the xsi:type name of this class
     */
    public function getXsiTypeName()
    {
        return self::XSI_TYPE;
    }
    public function __construct($searchParameters = null, $ideaType = null, $requestType = null, $requestedAttributeTypes = null, $paging = null, $localeCode = null, $currencyCode = null)
    {
        $this->searchParameters = $searchParameters;
        $this->ideaType = $ideaType;
        $this->requestType = $requestType;
        $this->requestedAttributeTypes = $requestedAttributeTypes;
        $this->paging = $paging;
        $this->localeCode = $localeCode;
        $this->currencyCode = $currencyCode;
    }
}
