<?php
/*
 * File generated by ClassyFile <https://github.com/onema/classyfile>
 * (c) 2016, Juan Manuel Torres
 *
 * For the full copyright and license information,
 * please view the LICENSE file that was distributed
 * with this source code.
 */
namespace Google\Api\Ads\AdWords\v201607;


/**
   * Contains a list of campaigns to perform a traffic estimate on.
   * @package Google_Api_Ads_AdWords_v201607
   * @subpackage v201607
   */
class TrafficEstimatorSelector
{
    const WSDL_NAMESPACE = 'https://adwords.google.com/api/adwords/o/v201607';
    const XSI_TYPE = 'TrafficEstimatorSelector';
    /**
     * @access public
     * @var CampaignEstimateRequest[]
     */
    public $campaignEstimateRequests;
    /**
     * @access public
     * @var boolean
     */
    public $platformEstimateRequested;
    /**
     * Gets the namesapce of this class
     * @return string the namespace of this class
     */
    public function getNamespace()
    {
        return self::WSDL_NAMESPACE;
    }
    /**
     * Gets the xsi:type name of this class
     * @return string the xsi:type name of this class
     */
    public function getXsiTypeName()
    {
        return self::XSI_TYPE;
    }
    public function __construct($campaignEstimateRequests = null, $platformEstimateRequested = null)
    {
        $this->campaignEstimateRequests = $campaignEstimateRequests;
        $this->platformEstimateRequested = $platformEstimateRequested;
    }
}
